#!/bin/sh

# Mount /persistent on top of overlay
PREREQ='overlayroot'

prereqs() {
  echo "$PREREQ"
}

case $1 in
prereqs)
  prereqs
  exit 0
  ;;
esac

# Get hostname
hostname=`hostname`
# Remove any domain parts
hostname=${hostname%%.*}

# Mount persistent directory from peer of nfsroot
nfspersistent=${nfsroot%/*}/persistent/${hostname}

# Mount the persistent filesystem
nfsmount ${nfspersistent} ${rootmnt}/persistent
